// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    GButton: typeof import('./components/atoms/GButton.vue')['default']
    GFadeTransition: typeof import('./components/atoms/GFadeTransition.vue')['default']
    GIcon: typeof import('./components/atoms/GIcon.vue')['default']
    GInputText: typeof import('./components/atoms/GInputText.vue')['default']
    GTitle: typeof import('./components/atoms/GTitle.vue')['default']
    Icon: typeof import('./components/atoms/Icon.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
